image:
  - Visual Studio 2019
  - Visual Studio 2022

platform: x64
configuration: Release

version: ci.{build}

build_script:
  - DIR C:\Libraries
  - DIR C:\Libraries\boost_1_83_0
  - DIR C:\Libraries\boost_1_78_0

